### ISSUE TITLE
There is no directories in the repository?

### ISSUE THREAD

**Issue by changyukang** [Michaelwan777/CS_Uni_Adelaide#1]
Hello, Michael, I am very thankful for your sharing. But I could not see any content in the repository, Is there anything wrong?

**Comment by changyukang** [comment]
I have solved the problem by changing the branch from "master" to "MCI". 
By the way, I still suggest that the master branch should be the same with MCI

**Comment by Michaelwan777** [comment]
> I have solved the problem by changing the branch from "master" to "MCI".
> By the way, I still suggest that the master branch should be the same with MCI
Thanks for your point, all users can restructure the branch. I just uploaded all courses materials into one major.

**Comment by Michaelwan777** [comment]
> I have solved the problem by changing the branch from "master" to "MCI".
> By the way, I still suggest that the master branch should be the same with MCI

@changyukang Thanks for your point, I just see this comment. I just uploaded all courses materials into one major. Cheers!

**Comment by changyukang** [comment]
Thanks~~, you are excellent !!

**Comment by Michaelwan777** [comment]
It's finished.
